---

services:

#############################
#RADARR
#############################

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/media/arr/radarr/config:/config
      - /mnt/media/arr/radarr/movies:/data/movies #optional
      - /mnt/media/arr/qbittorrent/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

#############################
#RADARR ANIME
#############################

  radarr-anime:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-anime
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/media/arr/radarr-anime/config:/config
      - /mnt/media/arr/radarr-anime/animemovies:/data/animemovies #optional
      - /mnt/media/arr/qbittorrent/downloads:/downloads #optional
    ports:
      - 7879:7878
    restart: unless-stopped

#############################
#SONARR
#############################

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/media/arr/sonarr/config:/config
      - /mnt/media/arr/sonarr/tv:/data/tv #optional
      - /mnt/media/arr/qbittorrent/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

#############################
#SONARR ANIME
#############################

  sonarr-anime:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-anime
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/media/arr/sonarr-anime/config:/config
      - /mnt/media/arr/sonarr-anime/animetv:/data/animetv #optional
      - /mnt/media/arr/qbittorrent/downloads:/downloads #optional
    ports:
      - 8988:8989
    restart: unless-stopped

#############################
#LIDARR
#############################

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/media/arr/lidarr/config:/config
      - /mnt/media/arr/lidarr/music:/data/music #optional
      - /mnt/media/arr/qbittorrent/downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped

#############################
#READARR
#############################

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/media/arr/readarr/config:/config
      - /mnt/media/arr/readarr/books:/data/books #optional
      - /mnt/media/arr/qbittorrent/downloads:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped

#############################
#PROWLARR
#############################

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/media/arr/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

#############################
#QBIT
#############################

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /mnt/media/arr/qbittorrent/config:/config
      - /mnt/media/arr/qbittorrent/downloads:/downloads #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
